name: Create a New Release

on:
  push:
    branches: [master]

jobs:
  conventional-commits:
    uses: ./.github/workflows/conventional-commits.yml

  checks:
    uses: ./.github/workflows/checks.yml

  build:
    needs: [lint, format, check-types]
    uses: ./.github/workflows/build.yml

  release:
    needs: [checks]
    uses: ./.github/workflows/create-release.yml
